use_frameworks!

target 'PKCHelper_Example' do
  pod 'PKCHelper', :path => '../'

  target 'PKCHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.4'
    pod 'Nimble', '~> 7.3.4'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.9.1'
  end
end
